# REST requests for use with the REST Client VSCode extension - https://marketplace.visualstudio.com/items?itemName=humao.rest-client

# Test GET challenge
GET http://localhost:7071/callback?hub.mode=subscribe&hub.challenge=mychallenge&verify_token=mytoken

### GET root
GET http://localhost:7071/start

### Test webhook POST - https://www.strava.com/activities/7366272349
POST http://localhost:7071/webhook HTTP/1.1
Content-Type: application/json

{
    "aspect_type": "create",
    "event_time": 1516126040,
    "object_id": 7366272349,
    "object_type": "activity",
    "owner_id": 1295848,
    "subscription_id": 120475,
    "updates": {
        "title": "Messy"
    }
}

### Test webhook POST - https://www.strava.com/activities/7366272349
POST {{$dotenv STRAVA_CALLBACK_URI}} HTTP/1.1
Content-Type: application/json

{
    "aspect_type": "create",
    "event_time": 1516126040,
    "object_id": 7366272349,
    "object_type": "activity",
    "owner_id": 1295848,
    "subscription_id": 120475,
    "updates": {
        "title": "Messy"
    }
}


### Test DELETE method
DELETE http://localhost:7071/api/webhook HTTP/1.1

### Get athlete info
GET https://www.strava.com/api/v3/athlete HTTP/1.1
Authorization: Bearer {{$dotenv STRAVA_ACCESS_TOKEN}}

### Get Activities
GET https://www.strava.com/api/v3/athlete/activities HTTP/1.1
Authorization: Bearer {{$dotenv STRAVA_ACCESS_TOKEN}}

### Get an activity
GET https://www.strava.com/api/v3/activities/7542422772 HTTP/1.1
Authorization: Bearer {{$dotenv STRAVA_ACCESS_TOKEN}}

### Get subscriptions
GET https://www.strava.com/api/v3/push_subscriptions
    ?client_id={{$dotenv STRAVA_CLIENT_ID}}
    &client_secret={{$dotenv STRAVA_CLIENT_SECRET}} HTTP/1.1

### Delete subscription
DELETE https://www.strava.com/api/v3/push_subscriptions/218490
    ?client_id={{$dotenv STRAVA_CLIENT_ID}}
    &client_secret={{$dotenv STRAVA_CLIENT_SECRET}} HTTP/1.1

### Get current weather from openweathermap
GET https://api.openweathermap.org/data/3.0/onecall
    ?lat={{$dotenv OWM_LAT}}
    &lon={{$dotenv OWM_LON}}
    &appid={{$dotenv OWM_API_KEY}} HTTP/1.1

### Get historical weather from openweathermap
GET https://api.openweathermap.org/data/3.0/onecall/timemachine
    ?lat={{$dotenv OWM_LAT}}
    &lon={{$dotenv OWM_LON}}
    &units=metric
    &appid={{$dotenv OWM_API_KEY}}
    &dt=1656070128 HTTP/1.1

### Alternate method using history api
GET https://api.openweathermap.org/data/2.5/history/city
    ?type=hour
    &lat={{$dotenv OWM_LAT}}
    &lon={{$dotenv OWM_LON}}
    &start=1518792774
    &end=1518794979
    &appid={{$dotenv OWM_API_KEY}} HTTP/1.1

